name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Show Properties
      run: |
        echo ${{github.ref}}
        echo ${{github.sha}}
        git diff ${{github.ref}}..${{github.sha}} --name-only
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml test
